#!/bin/sh

IMGPROXY_LOCAL_FILESYSTEM_ROOT="./backend/target/images" \
    IMGPROXY_KEY="70755b84bc80f295977454" \
    IMGPROXY_SALT="b293fdedb9628408fbe27b" \
    IMGPROXY_MAX_SRC_RESOLUTION="30.0" \
    IMGPROXY_USE_ETAG="true" \
    IMGPROXY_ENABLE_CLIENT_HINTS="true" \
    IMGPROXY_ENABLE_WEBP_DETECTION="true" \
    IMGPROXY_ENFORCE_WEBP="true" \
    IMGPROXY_ENABLE_DEBUG_HEADERS="true" \
    IMGPROXY_BIND=":8081" \
    imgproxy