micronaut:
  server:
    multipart:
      max-file-size: '100MB'
  application:
    name: imagehive
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    # e.g. jdbc:postgresql://localhost:5432/imagehive
    url: ${IMAGEHIVE_PG_JDBC_URL}
    username: ${IMAGEHIVE_PG_USER:postgres}
    password: ${IMAGEHIVE_PG_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
netty:
  default:
    allocator:
      max-order: 3

imagehive:
  application:
    image-base-path: "images"
  smtpmail:
    host: "localhost"
    port: "25"
    auth: true
    username: "dummy"
    password: "dummy"

