micronaut:
  server:
    multipart:
      max-file-size: '100MB'
      enabled: true
      disk: true
    # for tus file uploads
    cors:
      enabled: true
      configurations:
        ui:
          allowed-methods:
            - POST
            - DELETE
            - PATCH
            - HEAD
          exposed-headers:
            - Authorization
            - Location
            - Upload-Offset
            - Upload-Length
            - Tus-Resumable
            - Upload-Metadata
            - Upload-Defer-Length
            - Upload-Concat
            - Origin
            - X-Requested-With
            - X-Request-ID
            - X-HTTP-Method-Override
          allowed-headers:
            - Authorization
            - Location
            - Upload-Offset
            - Upload-Length
            - Tus-Resumable
            - Upload-Metadata
            - Upload-Defer-Length
            - Upload-Concat
            - Origin
            - X-Requested-With
            - X-Request-ID
            - X-HTTP-Method-Override
          allowed-origins:
            - http://localhost:3000
            - http://127.0.0.1:3000

    host: 0.0.0.0

  application:
    name: imagehive
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    # e.g. jdbc:postgresql://localhost:5432/imagehive
    url: ${IMAGEHIVE_PG_JDBC_URL}
    username: ${IMAGEHIVE_PG_USER:postgres}
    password: ${IMAGEHIVE_PG_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
netty:
  default:
    allocator:
      max-order: 3

imagehive:
  image-base-path: "images"
