/*
 * This file is generated by jOOQ.
 */
package com.github.gyrosofwar.imagehive.sql;

import com.github.gyrosofwar.imagehive.sql.tables.Album;
import com.github.gyrosofwar.imagehive.sql.tables.AlbumImage;
import com.github.gyrosofwar.imagehive.sql.tables.Image;
import com.github.gyrosofwar.imagehive.sql.tables.User;

/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table <code>public.album</code>.
   */
  public static final Album ALBUM = Album.ALBUM;

  /**
   * The table <code>public.album_image</code>.
   */
  public static final AlbumImage ALBUM_IMAGE = AlbumImage.ALBUM_IMAGE;

  /**
   * The table <code>public.image</code>.
   */
  public static final Image IMAGE = Image.IMAGE;

  /**
   * The table <code>public.user</code>.
   */
  public static final User USER = User.USER;
}
