/*
 * This file is generated by jOOQ.
 */
package com.github.gyrosofwar.imagehive.sql.tables;


import com.github.gyrosofwar.imagehive.sql.Indexes;
import com.github.gyrosofwar.imagehive.sql.Keys;
import com.github.gyrosofwar.imagehive.sql.Public;
import com.github.gyrosofwar.imagehive.sql.tables.records.AlbumRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Album extends TableImpl<AlbumRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.album</code>
     */
    public static final Album ALBUM = new Album();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlbumRecord> getRecordType() {
        return AlbumRecord.class;
    }

    /**
     * The column <code>public.album.id</code>.
     */
    public final TableField<AlbumRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.album.name</code>.
     */
    public final TableField<AlbumRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.album.description</code>.
     */
    public final TableField<AlbumRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.album.created_on</code>.
     */
    public final TableField<AlbumRecord, OffsetDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.album.owner_id</code>.
     */
    public final TableField<AlbumRecord, Long> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.album.thumbnail_id</code>.
     */
    public final TableField<AlbumRecord, UUID> THUMBNAIL_ID = createField(DSL.name("thumbnail_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.album.tags</code>.
     */
    public final TableField<AlbumRecord, String[]> TAGS = createField(DSL.name("tags"), SQLDataType.VARCHAR.nullable(false).array(), this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<AlbumRecord, Object> TS_VEC = createField(DSL.name("ts_vec"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tsvector\"").nullable(false), this, "");

    private Album(Name alias, Table<AlbumRecord> aliased) {
        this(alias, aliased, null);
    }

    private Album(Name alias, Table<AlbumRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.album</code> table reference
     */
    public Album(String alias) {
        this(DSL.name(alias), ALBUM);
    }

    /**
     * Create an aliased <code>public.album</code> table reference
     */
    public Album(Name alias) {
        this(alias, ALBUM);
    }

    /**
     * Create a <code>public.album</code> table reference
     */
    public Album() {
        this(DSL.name("album"), null);
    }

    public <O extends Record> Album(Table<O> child, ForeignKey<O, AlbumRecord> key) {
        super(child, key, ALBUM);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.FULLTEXT_ALBUM_IDX);
    }

    @Override
    public Identity<AlbumRecord, Long> getIdentity() {
        return (Identity<AlbumRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AlbumRecord> getPrimaryKey() {
        return Keys.ALBUM_PKEY;
    }

    @Override
    public List<ForeignKey<AlbumRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ALBUM__ALBUM_OWNER_ID_FKEY, Keys.ALBUM__ALBUM_THUMBNAIL_ID_FKEY);
    }

    private transient User _user;
    private transient Image _image;

    /**
     * Get the implicit join path to the <code>public.user</code> table.
     */
    public User user() {
        if (_user == null)
            _user = new User(this, Keys.ALBUM__ALBUM_OWNER_ID_FKEY);

        return _user;
    }

    /**
     * Get the implicit join path to the <code>public.image</code> table.
     */
    public Image image() {
        if (_image == null)
            _image = new Image(this, Keys.ALBUM__ALBUM_THUMBNAIL_ID_FKEY);

        return _image;
    }

    @Override
    public Album as(String alias) {
        return new Album(DSL.name(alias), this);
    }

    @Override
    public Album as(Name alias) {
        return new Album(alias, this);
    }

    @Override
    public Album as(Table<?> alias) {
        return new Album(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(String name) {
        return new Album(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(Name name) {
        return new Album(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(Table<?> name) {
        return new Album(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, OffsetDateTime, Long, UUID, String[], Object> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Long, ? super String, ? super String, ? super OffsetDateTime, ? super Long, ? super UUID, ? super String[], ? super Object, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Long, ? super String, ? super String, ? super OffsetDateTime, ? super Long, ? super UUID, ? super String[], ? super Object, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
