/*
 * This file is generated by jOOQ.
 */
package com.github.gyrosofwar.imagehive.sql.tables.pojos;

import java.io.Serializable;
import java.time.OffsetDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record Album(Long id, String name, OffsetDateTime createdOn, Long ownerId, String[] tags)
  implements Serializable {
  private static final long serialVersionUID = 1L;
}
