/*
 * This file is generated by jOOQ.
 */
package com.github.gyrosofwar.imagehive.sql.tables.pojos;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.jooq.JSONB;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record Image(
  UUID id,
  OffsetDateTime createdOn,
  Long ownerId,
  Integer height,
  Integer width,
  Object geoCoordinates,
  JSONB metadata,
  String[] tags
)
  implements Serializable {
  private static final long serialVersionUID = 1L;
}
