/* tslint:disable */
/* eslint-disable */
/**
 * Imagehive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from "../runtime"
/**
 *
 * @export
 * @interface ImageDTO
 */
export interface ImageDTO {
  /**
   *
   * @type {number}
   * @memberof ImageDTO
   */
  height: number
  /**
   *
   * @type {number}
   * @memberof ImageDTO
   */
  width: number
  /**
   *
   * @type {Date}
   * @memberof ImageDTO
   */
  createdOn: Date
  /**
   *
   * @type {Array<string>}
   * @memberof ImageDTO
   */
  tags: Array<string>
}

/**
 * Check if a given object implements the ImageDTO interface.
 */
export function instanceOfImageDTO(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "height" in value
  isInstance = isInstance && "width" in value
  isInstance = isInstance && "createdOn" in value
  isInstance = isInstance && "tags" in value

  return isInstance
}

export function ImageDTOFromJSON(json: any): ImageDTO {
  return ImageDTOFromJSONTyped(json, false)
}

export function ImageDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ImageDTO {
  if (json === undefined || json === null) {
    return json
  }
  return {
    height: json["height"],
    width: json["width"],
    createdOn: new Date(json["createdOn"]),
    tags: json["tags"],
  }
}

export function ImageDTOToJSON(value?: ImageDTO | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    height: value.height,
    width: value.width,
    createdOn: value.createdOn.toISOString(),
    tags: value.tags,
  }
}
