/* tslint:disable */
/* eslint-disable */
/**
 * Imagehive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists, mapValues} from "../runtime"
/**
 *
 * @export
 * @interface UserCreateDTO
 */
export interface UserCreateDTO {
  /**
   *
   * @type {string}
   * @memberof UserCreateDTO
   */
  username: string
  /**
   *
   * @type {string}
   * @memberof UserCreateDTO
   */
  email: string
  /**
   *
   * @type {string}
   * @memberof UserCreateDTO
   */
  password: string
  /**
   *
   * @type {boolean}
   * @memberof UserCreateDTO
   */
  admin: boolean
  /**
   *
   * @type {boolean}
   * @memberof UserCreateDTO
   */
  generatePassword: boolean
}

/**
 * Check if a given object implements the UserCreateDTO interface.
 */
export function instanceOfUserCreateDTO(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "username" in value
  isInstance = isInstance && "email" in value
  isInstance = isInstance && "password" in value
  isInstance = isInstance && "admin" in value
  isInstance = isInstance && "generatePassword" in value

  return isInstance
}

export function UserCreateDTOFromJSON(json: any): UserCreateDTO {
  return UserCreateDTOFromJSONTyped(json, false)
}

export function UserCreateDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserCreateDTO {
  if (json === undefined || json === null) {
    return json
  }
  return {
    username: json["username"],
    email: json["email"],
    password: json["password"],
    admin: json["admin"],
    generatePassword: json["generatePassword"],
  }
}

export function UserCreateDTOToJSON(value?: UserCreateDTO | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    username: value.username,
    email: value.email,
    password: value.password,
    admin: value.admin,
    generatePassword: value.generatePassword,
  }
}
