/*
 * This file is generated by jOOQ.
 */
package com.github.gyrosofwar.imagehive.sql;


import com.github.gyrosofwar.imagehive.sql.tables.Album;
import com.github.gyrosofwar.imagehive.sql.tables.Image;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FULLTEXT_ALBUM_IDX = Internal.createIndex(DSL.name("fulltext_album_idx"), Album.ALBUM, new OrderField[] { Album.ALBUM.TS_VEC }, false);
    public static final Index FULLTEXT_IMAGE_IDX = Internal.createIndex(DSL.name("fulltext_image_idx"), Image.IMAGE, new OrderField[] { Image.IMAGE.TS_VEC }, false);
}
