/*
 * This file is generated by jOOQ.
 */
package com.github.gyrosofwar.imagehive.sql;


import com.github.gyrosofwar.imagehive.sql.tables.Album;
import com.github.gyrosofwar.imagehive.sql.tables.AlbumImage;
import com.github.gyrosofwar.imagehive.sql.tables.Image;
import com.github.gyrosofwar.imagehive.sql.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.album</code>.
     */
    public final Album ALBUM = Album.ALBUM;

    /**
     * The table <code>public.album_image</code>.
     */
    public final AlbumImage ALBUM_IMAGE = AlbumImage.ALBUM_IMAGE;

    /**
     * The table <code>public.image</code>.
     */
    public final Image IMAGE = Image.IMAGE;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Album.ALBUM,
            AlbumImage.ALBUM_IMAGE,
            Image.IMAGE,
            User.USER
        );
    }
}
