micronaut:
  server:
    multipart:
      max-file-size: "100MB"
      enabled: true
      disk: true
    # for tus file uploads
    cors:
      enabled: true
      configurations:
        ui:
          single-header: true
          allowed-methods:
            - POST
            - DELETE
            - PATCH
            - HEAD
          exposed-headers:
            - Location
            - Upload-Offset
            - Upload-Length
          allowed-headers:
            - Authorization
            - Content-Type
            - Tus-Resumable
            - Upload-Offset
            - Upload-Length
            - Upload-Metadata
          allowed-origins:
            - http://localhost:5173
            - http://127.0.0.1:5173

    host: 0.0.0.0
    port: 8040
  application:
    name: imagehive
  security:
    authentication: bearer
    endpoints:
      login:
        path: /api/login
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
        generator:
          refresh-token:
            enabled: true
            secret: ${JWT_GENERATOR_REFRESH_TOKEN_SECRET:pleaseChangeThisSecretForANewOne}
          access-token:
            expiration: 28800
  http:
    client:
      read-timeout: 60s

datasources:
  default:
    # e.g. jdbc:postgresql://localhost:5432/imagehive
    url: ${IMAGEHIVE_PG_JDBC_URL}
    username: ${IMAGEHIVE_PG_USER:postgres}
    password: ${IMAGEHIVE_PG_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration

imagehive:
  image-base-path: "images"
  thumbnailer: JAVA

  lavis:
    enabled: true
    url: "http://localhost:5000"

  img-proxy:
    uri: "http://localhost:8081"
    key: "70755b84bc80f295977454"
    salt: "b293fdedb9628408fbe27b"

  smtpmail:
    host: "localhost"
    port: "25"
    auth: true
    username: "dummy"
    password: "dummy"

jackson:
  date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
