/*
 * This file is generated by jOOQ.
 */
package com.github.gyrosofwar.imagehive.sql.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record Image(
    UUID id,
    String title,
    String description,
    OffsetDateTime createdOn,
    OffsetDateTime capturedOn,
    Long ownerId,
    Integer width,
    Integer height,
    Double gpsLatitude,
    Double gpsLongitude,
    JSONB metadata,
    String[] tags,
    Boolean favorite,
    String filePath,
    JSONB geoJson,
    Object tsVec
) implements Serializable {

    private static final long serialVersionUID = 1L;

}
