/*
 * This file is generated by jOOQ.
 */
package com.github.gyrosofwar.imagehive.sql.tables.records;

import com.github.gyrosofwar.imagehive.sql.tables.User;
import java.time.OffsetDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord
  extends UpdatableRecordImpl<UserRecord>
  implements
    Record8<Long, String, String, String, Boolean, String, OffsetDateTime, OffsetDateTime> {

  private static final long serialVersionUID = 1L;

  /**
   * Setter for <code>public.user.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.user.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.user.username</code>.
   */
  public void setUsername(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.user.username</code>.
   */
  public String getUsername() {
    return (String) get(1);
  }

  /**
   * Setter for <code>public.user.email</code>.
   */
  public void setEmail(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>public.user.email</code>.
   */
  public String getEmail() {
    return (String) get(2);
  }

  /**
   * Setter for <code>public.user.password_hash</code>.
   */
  public void setPasswordHash(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>public.user.password_hash</code>.
   */
  public String getPasswordHash() {
    return (String) get(3);
  }

  /**
   * Setter for <code>public.user.admin</code>.
   */
  public void setAdmin(Boolean value) {
    set(4, value);
  }

  /**
   * Getter for <code>public.user.admin</code>.
   */
  public Boolean getAdmin() {
    return (Boolean) get(4);
  }

  /**
   * Setter for <code>public.user.totp_secret</code>.
   */
  public void setTotpSecret(String value) {
    set(5, value);
  }

  /**
   * Getter for <code>public.user.totp_secret</code>.
   */
  public String getTotpSecret() {
    return (String) get(5);
  }

  /**
   * Setter for <code>public.user.created_on</code>.
   */
  public void setCreatedOn(OffsetDateTime value) {
    set(6, value);
  }

  /**
   * Getter for <code>public.user.created_on</code>.
   */
  public OffsetDateTime getCreatedOn() {
    return (OffsetDateTime) get(6);
  }

  /**
   * Setter for <code>public.user.last_login</code>.
   */
  public void setLastLogin(OffsetDateTime value) {
    set(7, value);
  }

  /**
   * Getter for <code>public.user.last_login</code>.
   */
  public OffsetDateTime getLastLogin() {
    return (OffsetDateTime) get(7);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row8<Long, String, String, String, Boolean, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
    return (Row8) super.fieldsRow();
  }

  @Override
  public Row8<Long, String, String, String, Boolean, String, OffsetDateTime, OffsetDateTime> valuesRow() {
    return (Row8) super.valuesRow();
  }

  @Override
  public Field<Long> field1() {
    return User.USER.ID;
  }

  @Override
  public Field<String> field2() {
    return User.USER.USERNAME;
  }

  @Override
  public Field<String> field3() {
    return User.USER.EMAIL;
  }

  @Override
  public Field<String> field4() {
    return User.USER.PASSWORD_HASH;
  }

  @Override
  public Field<Boolean> field5() {
    return User.USER.ADMIN;
  }

  @Override
  public Field<String> field6() {
    return User.USER.TOTP_SECRET;
  }

  @Override
  public Field<OffsetDateTime> field7() {
    return User.USER.CREATED_ON;
  }

  @Override
  public Field<OffsetDateTime> field8() {
    return User.USER.LAST_LOGIN;
  }

  @Override
  public Long component1() {
    return getId();
  }

  @Override
  public String component2() {
    return getUsername();
  }

  @Override
  public String component3() {
    return getEmail();
  }

  @Override
  public String component4() {
    return getPasswordHash();
  }

  @Override
  public Boolean component5() {
    return getAdmin();
  }

  @Override
  public String component6() {
    return getTotpSecret();
  }

  @Override
  public OffsetDateTime component7() {
    return getCreatedOn();
  }

  @Override
  public OffsetDateTime component8() {
    return getLastLogin();
  }

  @Override
  public Long value1() {
    return getId();
  }

  @Override
  public String value2() {
    return getUsername();
  }

  @Override
  public String value3() {
    return getEmail();
  }

  @Override
  public String value4() {
    return getPasswordHash();
  }

  @Override
  public Boolean value5() {
    return getAdmin();
  }

  @Override
  public String value6() {
    return getTotpSecret();
  }

  @Override
  public OffsetDateTime value7() {
    return getCreatedOn();
  }

  @Override
  public OffsetDateTime value8() {
    return getLastLogin();
  }

  @Override
  public UserRecord value1(Long value) {
    setId(value);
    return this;
  }

  @Override
  public UserRecord value2(String value) {
    setUsername(value);
    return this;
  }

  @Override
  public UserRecord value3(String value) {
    setEmail(value);
    return this;
  }

  @Override
  public UserRecord value4(String value) {
    setPasswordHash(value);
    return this;
  }

  @Override
  public UserRecord value5(Boolean value) {
    setAdmin(value);
    return this;
  }

  @Override
  public UserRecord value6(String value) {
    setTotpSecret(value);
    return this;
  }

  @Override
  public UserRecord value7(OffsetDateTime value) {
    setCreatedOn(value);
    return this;
  }

  @Override
  public UserRecord value8(OffsetDateTime value) {
    setLastLogin(value);
    return this;
  }

  @Override
  public UserRecord values(
    Long value1,
    String value2,
    String value3,
    String value4,
    Boolean value5,
    String value6,
    OffsetDateTime value7,
    OffsetDateTime value8
  ) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached UserRecord
   */
  public UserRecord() {
    super(User.USER);
  }

  /**
   * Create a detached, initialised UserRecord
   */
  public UserRecord(
    Long id,
    String username,
    String email,
    String passwordHash,
    Boolean admin,
    String totpSecret,
    OffsetDateTime createdOn,
    OffsetDateTime lastLogin
  ) {
    super(User.USER);
    setId(id);
    setUsername(username);
    setEmail(email);
    setPasswordHash(passwordHash);
    setAdmin(admin);
    setTotpSecret(totpSecret);
    setCreatedOn(createdOn);
    setLastLogin(lastLogin);
  }

  /**
   * Create a detached, initialised UserRecord
   */
  public UserRecord(com.github.gyrosofwar.imagehive.sql.tables.pojos.User value) {
    super(User.USER);
    if (value != null) {
      setId(value.id());
      setUsername(value.username());
      setEmail(value.email());
      setPasswordHash(value.passwordHash());
      setAdmin(value.admin());
      setTotpSecret(value.totpSecret());
      setCreatedOn(value.createdOn());
      setLastLogin(value.lastLogin());
    }
  }
}
